all:
  hosts:
    master-1:
      ansible_host: 192.168.56.11
      ip: 192.168.56.11
      access_ip: 192.168.56.11
    master-2:
      ansible_host: 192.168.56.12
      ip: 192.168.56.12
      access_ip: 192.168.56.12
    node-1:
      ansible_host: 192.168.56.21
      ip: 192.168.56.21
      access_ip: 192.168.56.21
  children:
    kube_control_plane:
      hosts:
        master-1:
        master-2:
    kube_node:
      hosts:
        node-1:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
